### ISSUE TITLE
 Can the JSON Schema contributors organize themselves into an actual community? 

### ISSUE THREAD

**Issue by nickl-** [json-schema/project-info#2]
This rebuke from the google list.

>  Can the JSON Schema contributors organize themselves into an actual community?  With actual tools for voting on features, the ability to communicate a plan, draw additional commiters, etc etc?  
> THAT seemed to be the intent of the website that was taken down.  Do THAT and I am confident JSON Schema will take the world by storm as a standard... 

@json-schema what say you?

**Comment by fge** [comment]
A community is not made of tools but of people.

We are not enough to grant this kind of tools. If ever we do, I have a plan.

You'll notice I say "We". I still am a member of the community, just not an active one for the moment.

**Comment by nickl-** [comment]
@fge The question you fail to address is:

Can the contributors organize themselves into an actual community?
- With actual tools for voting on features
- The ability to communicate a plan
- Draw additional committers

How big does a community have to be for these items to become important from your perspective?

The community instead is the public, every user with an interest, that is watching these charades. If you consider that we've had 10,834 unique visitors is that substantial enough? Now consider out of the 10,834 we only have 4 active members. Would you agree that something is wrong with this picture? Do you mind stopping for a second so that we can try and work out why and change that?  Is this of any concern to you? It bugs the crap out of me! But we can't seem to manage 4 people let alone tens of thousands.

@fge I don't know, you feel compelled to highlight that you are saying "We" but all I read there is I am still a member, I have a plan. Please share this plan, if you don't mind. I am sure there are many others like this member, who would be happy to see a resolve.

**Comment by nickl-** [comment]
It is agreed then.
