### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by dmitryTsatsarin** [json-schema/project-info#3]
there is broken wiki link
https://github.com/json-schema/project-info/blob/master/json-schema/project-info/wiki/_pages
on this page:
https://github.com/json-schema/project-info/blob/master/README.md

**Comment by Relequestual** [comment]
@dmitryTsatsarin If you see this, please close this issue. Please see https://github.com/json-schema/project-info/issues/4 Thanks.

**Comment by dmitryTsatsarin** [comment]
@Relequestual ok
